---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: cloudflare-api-token
  namespace: dns
spec:
  encryptedData:
    api-token: AgBTD7cNkvegJECKrLhq5mmk0l/xZiTNZwCwCrBm7Jk1TinDN6OE55jo2C9nrZJqaWlZoTeMqXumzgXLSmNN+CU2ZaiK5/BA2sa3dOBcefSSLR60RbaXo/xbsyEgQryeRvMC1PM8vSiI6AMtWp8Uylto4mdKP9cER7mFGQ0F7dHpA6Ab5but6r755nSaoyJfqu0V8c+wL9Y7T9BO015iiCUI8my+/YOBpTZ4DtUGrGh+WyV7bTl2CqkEWHGTz+OhxWPsitfk5oH4lkAnoK37Q/1TT5+VphItmTdjpsFd0vZuhOQQYk00fRq4gmBaEomBaaLfMenG6BHQv22x1MDAUE0rUEhSLzM+tmO//coSDJ3mBQ3yRNkNxd3sB/iX3fT/EffkZLbA1zyiEX5tZW7zmaWCAN1qaZme5L3AKmKcGl/gtGNpeEGGjflIZcsHmQ8bITTeG2rfcApEozoXhfHin6/wBAD2xR8IE0kNbI7xBlf7FE2H4MgfqhJ4cpQxAUAqPfjJ42UgwcWECZ+SeslvC/3Nfg+dFGotQbd8g/Cg1WayGKjBWRqMJHGEMLlHqc0F13MG7nbiCTXgEyx24yeku2u5mSQyrYoafNlP63lmn1kd5ozXCUjGQPZKWKj0rKfQ2G+BjHP9rrnXnHlADdV1NwvgbuJK0E7gYbxd3a+spyIJsbvi7RaujZV42ziK8ro0b7eu+TSzxiPMiwmd76OPIlC/s2L2essdDt7MyW/oq+gvz/Odp0pTSiGp
  template:
    metadata:
      name: cloudflare-api-token
      namespace: dns
