apiVersion: cilium.io/v2
kind: CiliumLoadBalancerIPPool
metadata:
  name: homelab-pool
spec:
  blocks:
    - start: 192.168.30.200
      stop: 192.168.30.250
  serviceSelector:
    matchLabels:
      l2.cilium.io/ip-pool: default
