apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - https://github.com/grafana/grafana-operator/releases/download/v5.15.1/kustomize-cluster_scoped.yaml
  - grafana.yaml
  - ingress.yaml
  - sealedsecret-grafana-admin.yaml
  - datasources/prometheus-operated.yaml
  - datasources/alertmanager-operated.yaml

patches:
  - target:
      kind: CustomResourceDefinition
      name: grafanas.grafana.integreatly.org
    patch: |-
      apiVersion: apiextensions.k8s.io/v1
      kind: CustomResourceDefinition
      metadata:
        annotations:
          argocd.argoproj.io/sync-options: Replace=true
        name: grafanas.grafana.integreatly.org
