apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - application.yaml
  - grafana.yaml
  - ingress.yaml
  - sealedsecret-grafana-admin.yaml
  - datasources/prometheus-operated.yaml
  - datasources/alertmanager-operated.yaml
