apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - argocd-metrics.yaml
  - argocd-server-metrics.yaml
  - argocd-repo-server.yaml
  - argocd-applicationset-controller.yaml
