apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: cert-manager

resources:
  - https://github.com/cert-manager/cert-manager/releases/download/v1.16.2/cert-manager.yaml
  - cluster-issuer.yaml
  - sealedsecret-cloudflare-cert-manager.yaml

# Fix for https://github.com/cert-manager/cert-manager/issues/6716
# When namespace: is set, kustomize moves leader election RBAC from kube-system
# to cert-manager namespace, so we need to configure leader election namespace
patches:
  - target:
      kind: Deployment
      name: cert-manager
    patch: |-
      - op: add
        path: /spec/template/spec/containers/0/args/-
        value: --leader-election-namespace=cert-manager
  - target:
      kind: Deployment
      name: cert-manager-cainjector
    patch: |-
      - op: add
        path: /spec/template/spec/containers/0/args/-
        value: --leader-election-namespace=cert-manager
