apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: csi-proxmox

resources:
  - sealedsecret-proxmox-csi.yaml
  - storage-class.yaml
  - https://raw.githubusercontent.com/sergelogvinov/proxmox-csi-plugin/v0.16.0/docs/deploy/proxmox-csi-plugin.yml
