apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - proxmox-csi-config.yaml
  - storage-classes.yaml
  - https://raw.githubusercontent.com/sergelogvinov/proxmox-csi-plugin/v0.16.0/docs/deploy/proxmox-csi-plugin.yml
