apiVersion: v1
kind: Secret
metadata:
  name: proxmox-csi-plugin
  namespace: csi-proxmox
stringData:
  config.yaml: |
    clusters:
      - url: "https://draco.lab.home:8006/api2/json"
        insecure: true
        token_id: "kubernetes-csi@pve!csi"
        token_secret: "<PVE_API_TOKEN>"
        region: homelab
